[package]
name = "paul-term"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
nix = {version = "0.29.0", default-features = false, features = ["term", "process", "fs"]}
